project:
  type: website
  output-dir: docs

website:
  title: "Cursos"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Inicio"
        href: index.qmd
      - section: "Cursos"
        contents:
          - text: "Agentes"
            href: https://dgonxalex80.github.io/agentes/
          - text: "Arquitectura"
            href: https://dgonxalex80.github.io/arquitectura/
          - text: "Backend"
            href: https://dgonxalex80.github.io/backend/
          - text: "Camino"
            href: https://dgonxalex80.github.io/camino/
          - text: "Cancionero"
            href: https://dgonxalex80.github.io/cancionero/
          - text: "Carro"
            href: https://dgonxalex80.github.io/carro/
          - text: "Cocina"
            href: https://dgonxalex80.github.io/cocina/
          - text: "Computacion"
            href: https://dgonxalex80.github.io/computacion/
          - text: "DaVinci"
            href: https://dgonxalex80.github.io/davinci/
          - text: "Docker"
            href: https://dgonxalex80.github.io/docker/
          - text: "FIFA 2026"
            href: https://dgonxalex80.github.io/fifa2026/
          - text: "GitHub"
            href: https://dgonxalex80.github.io/github/
          - text: "Linux"
            href: https://dgonxalex80.github.io/linux/
          - text: "LWMMM"
            href: https://dgonxalex80.github.io/LWMMM/
          - text: "MMM"
            href: https://dgonxalex80.github.io/mmm/
          - text: "OBS"
            href: https://dgonxalex80.github.io/obs/
          - text: "Ollama"
            href: https://dgonxalex80.github.io/ollama/
          - text: "Positron"
            href: https://dgonxalex80.github.io/positron/
          - text: "Python"
            href: https://dgonxalex80.github.io/python/
          - text: "Quarto"
            href: https://dgonxalex80.github.io/quarto/
          - text: "RStudio"
            href: https://dgonxalex80.github.io/rstudio/
          - text: "Salud"
            href: https://dgonxalex80.github.io/salud/
          - text: "Servidor"
            href: https://dgonxalex80.github.io/servidor/
          - text: "Ubuntu"
            href: https://dgonxalex80.github.io/ubuntu/
          - text: "VSCode"
            href: https://dgonxalex80.github.io/vscode/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    include-in-header:
      text: |
        <link rel="icon" type="image/jpeg" href="img/escuela">
        <link rel="apple-touch-icon" sizes="180x180" href="img/escuela">
